import * as path from 'node:path';

/**
 * 
 * @internal
 */
export function applyFallbackRecipients(array: Array<any>, fallback: any): Array<any> {
  if (array.length === 0) {
    array.push(fallback);
  }
  return array;
}

/**
 * 
 * @internal
 */
export function changeFileExtension(fileName: string, newExt: string): string {
  const parsed = path.parse(fileName);
  return (parsed.dir ? parsed.dir + path.sep : "") + parsed.name + newExt;
}

/**
 * 
 * @internal
 */
export function convertToUint8Array(attachmentStream: ArrayBuffer | undefined): Uint8Array {
  if (attachmentStream instanceof ArrayBuffer) {
    return new Uint8Array(attachmentStream);
  }
  return new Uint8Array(0);
}

/**
 * 
 * Partially generated by model-router (2025-11-18)
 * 
 * @internal
 */
export function formatDateForEML(date: Date): string {
  const weekDays = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
  const shortMonths = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

  const weekDay = weekDays[date.getUTCDay()];
  const dayOfMonth = date.getUTCDate().toString().padStart(2, '0');
  const month = shortMonths[date.getUTCMonth()];
  const year = date.getUTCFullYear();
  const hours = date.getUTCHours().toString().padStart(2, '0');
  const minutes = date.getUTCMinutes().toString().padStart(2, '0');
  const seconds = date.getUTCSeconds().toString().padStart(2, '0');

  const offset = 0; // date.getTimezoneOffset();
  const offsetHours = Math.floor(Math.abs(offset) / 60).toString().padStart(2, '0');
  const offsetMinutes = (Math.abs(offset) % 60).toString().padStart(2, '0');
  const sign = offset <= 0 ? '+' : '-';

  return `${weekDay}, ${dayOfMonth} ${month} ${year} ${hours}:${minutes}:${seconds} ${sign}${offsetHours}${offsetMinutes}`;
}